import {
  AlarmClockCheck,
  ArrowLeftRight,
  ArrowRight,
  BadgeCheck,
  Boxes,
  Building2,
  CalendarClock,
  CalendarDays,
  ClipboardList,
  Clock,
  Compass,
  ConciergeBell,
  Carrot,
  CupSoda,
  FileCheck2,
  Handshake,
  Headset,
  Hotel,
  MapPin,
  MapPinned,
  MessageCircle,
  Milk,
  PackageCheck,
  PackageSearch,
  Phone,
  Mail,
  Receipt,
  RotateCcw,
  Route,
  ScrollText,
  ShieldCheck,
  SprayCan,
  Star,
  Tent,
  Timer,
  Truck,
  UtensilsCrossed,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  "alarm-check": AlarmClockCheck,
  "arrow-lr": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "badge-check": BadgeCheck,
  boxes: Boxes,
  building: Building2,
  "calendar-clock": CalendarClock,
  calendar: CalendarDays,
  clipboard: ClipboardList,
  clock: Clock,
  compass: Compass,
  bell: ConciergeBell,
  carrot: Carrot,
  drink: CupSoda,
  "file-check": FileCheck2,
  handshake: Handshake,
  headset: Headset,
  hotel: Hotel,
  pin: MapPin,
  "pin-route": MapPinned,
  whatsapp: MessageCircle,
  milk: Milk,
  "package-check": PackageCheck,
  "package-search": PackageSearch,
  phone: Phone,
  mail: Mail,
  receipt: Receipt,
  "rotate-back": RotateCcw,
  route: Route,
  scroll: ScrollText,
  shield: ShieldCheck,
  spray: SprayCan,
  star: Star,
  tent: Tent,
  timer: Timer,
  truck: Truck,
  utensils: UtensilsCrossed,
  wrench: Wrench,
  zap: Zap,
};

export function Icon({
  name,
  className = "h-5 w-5",
  strokeWidth = 1.6,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = map[name] ?? PackageSearch;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden />;
}
